// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvkbbtfcsxpjxlezfrwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2a2JidGZjc3hwanhsZXpmcndwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMTI5NjcsImV4cCI6MjA3MDU4ODk2N30.SPnPUp4pXBAuXqfquV4TiBUkD5JYqM2SKq6-njM5Er0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});