name: Deploy Vite + React to GitHub Pages

on:
  push:
    branches:
      - main  # roda sempre que der push no main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checa o código
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Instala dependências
      - name: Install dependencies
        run: npm install

      # 4️⃣ Build do projeto
      - name: Build project
        run: npm run build

      # 5️⃣ Deploy pro GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist   # ⚡ pasta de saída do Vite
