name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Toda vez que der push no main, deploy automático

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código
        uses: actions/checkout@v3

      # Se tu tiver build, tipo React, Next ou outro framework, adiciona o build aqui
      - name: Instalar dependências
        run: |
          npm install

      - name: Build do projeto
        run: |
          npm run build  # ou yarn build, depende do teu setup

      - name: Deploy para GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # ou ./out, ./dist, depende do teu projeto
